### PR TITLE
add file benchmark/.nosearch

### PR DESCRIPTION
**Pull request by tarsius**
This keeps `normal-top-level-add-subdirs-to-load-path` and similar tools from
adding "lib/" to the `load-path` or otherwise considering the bundled libraries
to be part of the package.

Please don't forget to sync this to the Elpa repository after merging. Thanks.

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
If I understand correctly, this is to avoid adding the `fixtures/` directory to the `load-path`, which coincidentally would cause outdated Emacs core packages to be loaded?

If so, I believe these files should be added to `benchmark/fixtures/` and `test/fixtures/` instead.

**Comment by tarsius** [comment]
Yes and yes. I have updated the pr accordingly.

**Comment by jacksonrayhamilton** [comment]
Great, thanks!

**Comment by tarsius** [comment]
Thanks to you too!

**Pull request merged**
